# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AnotherTravelApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AnotherTravelApp

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  
  target 'AnotherTravelAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AnotherTravelApp-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AnotherTravelApp-tvOS

  target 'AnotherTravelApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
